modLoader="javafml"
loaderVersion="*"
license="${license}"

[[mods]]
modId="${id}"
displayName="${name}"
description="${description}"
authors="${authors}"
version="${version}"
logoFile="assets/${id}/icon.png"
logoBlur=false